# @Author: guiguan
# @Date:   2017-02-15T07:18:20+11:00
# @Last modified by:   guiguan
# @Last modified time: 2017-06-20T15:18:44+10:00

inlinks:
  - dbkoda-ui
  - dbkoda-controller
outlinks:
  - dbkoda-mac
volumes:
  - type: yarn-cache
  - srcNode: dbkoda-ui
    srcPath: src/components/TreeActionPanel/DialogDefinitions
    tgtPath: src/tests/tree/actions/uiDefinitions/ddd
    type: link
  - srcNode: dbkoda-ui
    srcPath: src/components/TreeActionPanel/tests
    tgtPath: src/tests/tree/actions/uiDefinitions/inputAndTest
    type: link
  - srcNode: dbkoda-controller
    srcPath: .
    tgtPath: build/controller
    type: link
  - srcNode: dbkoda-ui
    srcPath: dist/ui
    tgtPath: build/controller/public/ui
    type: link
